export const LOCATIONS = {
  indian_cities: [
    'Mumbai, India',
    'Delhi, India',
    'Bangalore, India',
    'Hyderabad, India',
    'Ahmedabad, India',
    'Chennai, India',
    'Kolkata, India',
    'Pune, India',
    'Jaipur, India',
    'Surat, India',
    'Lucknow, India',
    'Kanpur, India',
    'Nagpur, India',
    'Indore, India',
    'Thane, India',
    'Bhopal, India',
    'Visakhapatnam, India',
    'Pimpri-Chinchwad, India',
    'Patna, India',
    'Vadodara, India',
    'Ghaziabad, India',
    'Ludhiana, India',
    'Agra, India',
    'Nashik, India',
    'Faridabad, India',
    'Meerut, India',
    'Rajkot, India',
    'Kalyan-Dombivali, India',
    'Vasai-Virar, India',
    'Varanasi, India',
  ],
  american_cities: [
    'New York, USA',
    'Los Angeles, USA',
    'Chicago, USA',
    'Houston, USA',
    'Phoenix, USA',
    'Philadelphia, USA',
    'San Antonio, USA',
    'San Diego, USA',
    'Dallas, USA',
    'San Jose, USA',
    'Austin, USA',
    'Jacksonville, USA',
    'Fort Worth, USA',
    'Columbus, USA',
    'San Francisco, USA',
    'Charlotte, USA',
    'Indianapolis, USA',
    'Seattle, USA',
    'Denver, USA',
    'Boston, USA',
    'Las Vegas, USA',
    'Miami, USA',
    'Atlanta, USA',
    'Portland, USA',
    'Detroit, USA',
  ],
  world_cities: [
    'London, United Kingdom',
    'Paris, France',
    'Berlin, Germany',
    'Madrid, Spain',
    'Rome, Italy',
    'Amsterdam, Netherlands',
    'Brussels, Belgium',
    'Vienna, Austria',
    'Tokyo, Japan',
    'Beijing, China',
    'Shanghai, China',
    'Hong Kong, China',
    'Seoul, South Korea',
    'Singapore, Singapore',
    'Dubai, UAE',
    'Abu Dhabi, UAE',
    'Sydney, Australia',
    'Melbourne, Australia',
    'Toronto, Canada',
    'Vancouver, Canada',
    'Mexico City, Mexico',
    'São Paulo, Brazil',
    'Buenos Aires, Argentina',
    'Moscow, Russia',
    'Istanbul, Turkey',
    'Cairo, Egypt',
    'Johannesburg, South Africa',
    'Lagos, Nigeria',
    'Nairobi, Kenya',
    'Bangkok, Thailand',
  ],
};
